CREATE TABLE IF NOT EXISTS AUTHOR(
    AUTHOR_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME TEXT
) ;

CREATE TABLE IF NOT EXISTS CATEGORY(
    CATEGORY_ID VARCHAR(256) PRIMARY KEY,
    CATEGORY VARCHAR(1000)
);

--'id','title','category_code','authors','published_date','updated_date','summary','summary_word_count'

CREATE TABLE IF NOT EXISTS PAPERS(
    ID VARCHAR(256) PRIMARY KEY,
    TITLE VARCHAR(1000),
    CATEGORY_CODE VARCHAR(256),
    AUTHORS TEXT,
    PUBLISHED_DATE DATE,
    UPDATED_DATE DATE,
    SUMMARY VARCHAR(4000),
    SUMMARY_WORD_COUNT NUMERIC
);